```{r}
#| echo: false

if (file.exists(table_dir)) {
  # Load in rda files created by:
  # r4ss::table_exec_summary
  # r4ss::table_pars
  # r4ss::table_parcounts
  
  all_files <- list.files(table_dir)
  all_rda_files <- all_files[grep(".rda", all_files)]
  for (a in 1:length(all_rda_files)) {
    load(file.path(table_dir, all_rda_files[a]))
  }
  
  catches_es_table <- catches_es$table
  catches_es_cap <- catches_es$cap
  rm(catches_es)
  
  ssb_es_table <- ssb_es$table
  #ssb_es_table$`Spawning output`<-round(ssb_es_table$`Spawning output`,3)
  #ssb_es_table$`Upper Interval (mt)`<-round(ssb_es_table$`Upper Interval (mt)`,3)
  ssb_es_table$`Lower Interval (mt)`[ssb_es_table$`Lower Interval (mt)`<0]<-"<0.001"
  colnames(ssb_es_table)[2]<-"Spawning output (trillions of eggs)"
  ssb_es_cap <- ssb_es$cap
  rm(ssb_es)
  
  recr_es_table <- recr_es$table
  #recr_es_table$`Lower Interval`[recr_es_table$`Lower Interval`<0]<-"<1"
  recr_es_cap <- recr_es$cap
  rm(recr_es)
  
  spr_es_table <- spr_es$table
  spr_es_table$`Lower Interval (SPR)`[spr_es_table$`Lower Interval (SPR)`<0]<-"<0.001"
  spr_es_table$`Lower Interval (Rate)`[spr_es_table$`Lower Interval (Rate)`<0]<-"<0.001"
  spr_es_cap <- spr_es$cap
  rm(spr_es)
  
  
  reference_points_table <- reference_points$table
  reference_points_table$`Lower Interval`[reference_points_table$`Lower Interval`<0]<-"<1"
  reference_points_table$`Lower Interval`[reference_points_table$`Lower Interval`!="<1"&!is.na(reference_points_table$`Lower Interval`)]<-round(as.numeric(reference_points_table$`Lower Interval`[reference_points_table$`Lower Interval`!="<1"&!is.na(reference_points_table$`Lower Interval`)]),3)
  reference_points_cap <- reference_points$cap
  reference_points_cap<-"Summary of reference points and management quantities, including estimates of the 95 percent confidence intervals. SO is spawning output (in trillions of eggs), SPR is the spawning potential ratio, and MSY is maximum sustainable yield."
  rm(reference_points)
  
  recent_management_table <- recent_management$table
  recent_management_cap <- recent_management$cap
  rm(recent_management)
    
  projections_table <- projections$table
  projections_table[1,2:3]<-c(238,189)
  projections_table[2,2:3]<-c(237,187)
  colnames(projections_table)[9]<-"Spawning output (trillions of eggs)"
  projections_cap <- projections$cap
  rm(projections)
  
  compweight_table <- table_compweight$table
  compweight_cap <- table_compweight$cap
  rm(table_compweight)
  
  config_table <- table_config$table
  config_cap <- table_config$cap
  rm(table_config)
  
  parcount_table <- table_parcounts$table
  parcount_cap <- table_parcounts$cap
  rm(table_parcounts)
  
  par_table <- table_pars$table
  par_cap <- table_pars$cap
  rm(table_pars)
  
  time_series_table <- time_series$table
  time_series_cap <- time_series$cap
  rm(time_series)
  
  eval_tables <- TRUE
} else {
  eval_tables <- FALSE
}

```


```{r}
#| echo: false

  time_series_table[, "Spawning output"] <- 
    round(time_series_table[, "Spawning output"], 0)
  time_series_table[, "Fraction Unfished"] <- 
    round(time_series_table[, "Fraction Unfished"], 3)
  time_series_table[, "Age-0 Recruits (1,000s)"] <- 
    round(time_series_table[, "Age-0 Recruits (1,000s)"], 0)
  time_series_table[, "Total Mortality (mt)"] <- 
    round(time_series_table[, "Total Mortality (mt)"], 0)
  time_series_table[, (ncol(time_series_table) -1):ncol(time_series_table)] <- 
    round(time_series_table[, (ncol(time_series_table) -1):ncol(time_series_table)], 3)

```



<!-- Read in models for decision table as well as caption -->
```{r}
#| eval: true
#| warning: false
#| echo: false
#| message: false

mod_low_A <- r4ss::SS_output(here::here("Document/report/Decision Table/Low"),    
  SpawnOutputLabel = "Spawning output (trillions of eggs)", printstats = FALSE, verbose = FALSE)

mod_base_A <- r4ss::SS_output(here::here("Document/report/Decision Table/Reference"),    
  SpawnOutputLabel = "Spawning output (trillions of eggs)", printstats = FALSE, verbose = FALSE)

mod_high_A <- r4ss::SS_output(here::here("Document/report/Decision Table/High"),    
  SpawnOutputLabel = "Spawning output (trillions of eggs)", printstats = FALSE, verbose = FALSE)

```
