# Introduction

Rougheye (*Sebastes aleutianus*) and Blackspotted (*Sebastes melanostictus*) rockfishes are two species that form one management complex of `r Spp` (RE/BS). 

Rougheye Rockfish are a long-lived rockfish named after a series of 2-10 spines along the lower rim of their eyes.  They have also been called Blackthroat or Blacktip Rockfish [@love_rockfishes_2002; @love_certainly_2011]. Blackspotted Rockfish are distributed in similar locations as Rougheye Rockfish and it is very difficult to visually distinguish the two species. These two species may hybridize on occasion [@love_certainly_2011].  

It has only been from recent genetic studies that these two separate species have been identified [@gharrett_genetically_2006; @hawkins_genetic_2005] and have had phenotypic characteristics useful for distinguishing the species in the field identified [@gharrett_genetically_2006; @orr_species_2008].  Before then, data were available for one species called Rougheye Rockfish that included Rougheye Rockfish and Blackspotted Rockfish.  Due to the difficulty in distinguishing these two species and the lack of historical separation of the species in all of the data, this assessment combines any data for Blackspotted Rockfish with Rougheye Rockfish into `r Spp_short` and provides management advice for the two species combined. These species are also closely related to Shortraker Rockfish (*Sebastes borealis*) and are sometimes difficult to distinguish from Shortraker Rockfish without looking at the gill rakers.  

## Stock Structure {#sec-stock_structure}

There are at least two questions to think about when considering stock structure for `r Spp_short` when doing a stock assessment.

* Since Rougheye and Blackspotted Rockfishes are two different species, can they be separated as two stocks and conduct separate assessments? 

Rougheye Rockfish were first described in 1811 as *Perca variabilis* by German zoologist Peter Simon Pallas [@jordan_fishes_1898], and assigned to various taxa at least 15 times since [@love_rockfishes_2002]. Some descriptions noted both light and dark color morphs, which, along with possible confusion with several morphologically similar co-occurring species (e.g., *Sebastes borealis* and *Sebastes melanostomus*), have contributed to the persistent ambiguity in formal descriptions of Rougheye Rockfish [@orr_species_2008]. The first genetic studies conducted in the late 1960s and early 1970s [@tsuyuki_contribution_1968; @tsuyuki_analyses_1970] observed diversity suggestive of two genetic types within specimens identified as Rougheye Rockfish. Allozyme studies conducted over the next two decades [@seeb_biochemical_1986; @hawkins_genetic_1997; @hawkins_genetic_2005] provided additional evidence suggesting two separate genetic types within field-identified Rougheye Rockfish.  Genetic variation between the two types, supported by both nuclear and mitochondrial DNA, was determined to be sufficiently conclusive to separate two species: “Type I” and “Type II” Rougheye Rockfish [@gharrett_two_2005]. Meristic and morphometric comparisons of the two species suggested certain characters, such as gill raker counts and length, snout length, anal base length, and pectoral fin base, were significantly different, and in combination could reliably, though not definitively, distinguish between the species [@gharrett_genetically_2006]. The two separate species were formally re-described by @orr_species_2008 with the Type II group retaining *Sebastes aleutianus* and the common name Rougheye Rockfish.  Blackspotted Rockfish was proposed as the common name for the Type I group along with the scientific name of *Sebastes melanostictus*, re-establishing nomenclature from one of the species complex’s earlier descriptions [@matsubara_1934].

These two species remain difficult to consistently differentiate visually in the catch, thus are still commonly reported and treated as a species complex. Otolith morphometrics (e.g., shape, size, weight) have shown some promise in possibly identifying these species in Alaskan waters (97.3% Blackspotted and 86.2% of Rougheye rockfishes were accurately identified) and possibly using older otoliths to break out historical information by species [@harris_using_2019]. Frey et al. (in prep.) provided insight into the ability of the Northwest Fisheries Science Center West Coast Groundfish Bottom Trawl Survey biologists to identify the two species, with 90% of genetically identified Rougheye Rockfish being correctly identified in the field. When mis-identifications occurred, it was usually a Blackspotted rockfish being mis-identified as a Rougheye Rockfish. There were few mis-identifications when a fish was identified as a Blackspotted rockfish. While this is promising for potential future species-specific data coming from the survey, it does not alleviate the historical problem of separating fishery data into the two species. Frey et al. (in prep.) therefore also considered whether ecological factors like depth or latitude could help separate samples by species. They found that both species occur within the range of this assessment’s considered areas (California to Washington), and heavily spatially overlap. Interestingly, there seem to be relative hot spots for these species where one species is more common than the other, and in general, Rougheye Rockfish seems to be more common than Blackspotted Rockfish; however, Blackspotted Rockfish may be the more common of the two in parts of Alaska [@gharrett_two_2005; @hawkins_genetic_2005; @orr_species_2008]. 

Despite recent advances in species identification of Rougheye Rockfish and Blackspotted Rockfish as genetically distinct species, there is little ability to separate current or historical fishery data reliably in order to separate these two species into two stocks. Therefore, this assessment maintains a species complex approach, though given absolute presence off the U.S. West Coast, this may be considered more of a Rougheye than a Blackspotted Rockfish stock assessment. We also note that throughout the range of these stocks, all current assessments to this point have maintained a species complex approach. While we treat these species as one assessed stock complex, we recognize and are mindful of the above species distinctions as we conduct our analyses.

* Both species range into Canada and Alaska – are they one stock? 

While genetics studies have focused mostly on identification of the two species, little is known about the population structure of either species. This assessment and the 2013 assessment [@hicks_status_2013] represent the most southerly range of these species. Comparing the absolute abundance of the 2013 assessment to the most current estimates of the Alaskan stocks, the absolute number in this southerly range is much smaller than in the Gulf of Alaska (GOA), but higher than in the Bering Sea/Aleutian Island (BSAI) stock (@fig-SO_comp). The two smaller stocks have similar trends of decline and stabilization, whereas the higher biomass GOA stock looks to have not dropped at all over the time period considered (@fig-RSS_comp). In spite of uncertainty in the stock structure, we assume here that the West Coast stocks of `r Spp_short` are distinct management units from those in Alaska.

## Distribution 
`r Spp_short` range from northern California up to and throughout Alaska and into Japan [@gharrett_two_2005; @hawkins_genetic_2005; @orr_species_2008]. Both are long-lived (>100 years), with Rougheye Rockfish having the distinction of the oldest ever aged *Sebastes* species at 205 years old [@munkMaximumAgesGroundfishes2001]. They both greatly overlap in latitude and depth (shallower than 100 m to at least 439 m), and are generally considered slope rockfish, with an ontogenetic shift from shallower to deeper, and adults commonly found at 360 m (around 200 fathoms). Rougheye seems to be proportionally more abundant when survey samples are genetically identified, and Blackspotted Rockfish tend to be found, on average, deeper than Rougheye Rockfish [@hawkins_genetic_2005; @orr_species_2008]. 

`r Spp_short` are often associated with structure, such as hard, rocky bottoms and steep habitats. They are rarely found on the deep flats. They can be found alone or in aggregations [@love_rockfishes_2002], with aggregations often differentiated by age.  Younger fish may school and are often found in shallower waters on the shelf, junveiles and subadults can be found together, and larger fish may form larger aggregations during the autumn and winter. 

This assessment treats the U.S. `r Spp_short` resource from the Mexican border to the Canadian border as a single coastwide stock (@fig-map). The U.S.-Canadian border is the northern boundary for the assessed stock, although the basis for this choice is due to political and current management needs rather than the population dynamics. The assessment excludes consideration of the Salish Sea. `r Spp_short` primarily occur in the the northern part of the assessed area  (@fig-cpue-map).

## Life History

Like all *Sebastes* species, `r Spp_short` give birth to live young. Parturition has been documented between February and June with larvae lengths at parturition are between 4.5-5.3 mm [@love_rockfishes_2002]. @dick_meta-analysis_2017 showed that rockfishes exhibit a non-proportional relationship of fecundity to weight, with larger individuals producing more eggs than expected only by weight. Although neither Rougheye nor Blackspotted Rockfishes have a species- or subfamily-specific estimate for this relationship,  this stock assessment uses the unobserved genus *Sebastes* values to inform fecundity to weight relationship for `r Spp_short`.

A wide range of prey items make up the diet of `r Spp_short`.  Crangonid and pandalid shrimps make up the majority of their diets, with larger individuals, greater than 30 cm, feeding upon other fishes [@love_certainly_2011].  They are also known to feed upon gammarid amphipods, mysids, crabs, polychaetes, and octopuses [@love_rockfishes_2002; @love_certainly_2011].

## Ecosystem Considerations

Rougheye Rockfish are one of the larger species of rockfish. They occupy shelf areas when they are young and move into deeper slope waters with age. As they age, they tend to become more solitary, but may form aggregations during the spawning season [@love_certainly_2011]. Due to a paucity of life-history data for Rougheye Rockfish, most ecosystem considerations are implied from the understanding of rockfishes in general. Recruitment drivers of `r Spp_short` are not well understood. Patterns in abundance of young-of-year rockfishes often covary through time across species of rockfish [@field_2021] indicating shared responses to ocenaographic and ecological conditions which could inform patterns in recruitment for species that are rarley caught in juvenile surveys, such as `r Spp_short`. For species that are primarily located north of Cape Mendocino, 2021 and 2023 indicate good recruitment years [@gasbarro_2025], although it is uncertain how well this trend applies to `r Spp_short`. The specific pathways through which environmental conditions exert influence on `r Spp_short` dynamics are unclear; however, changes in water temperature and currents, the amount and timing of upwelling, and source water variability are all possible drivers.

The largest components of `r Spp_short` diet in Alaska is pandalis and hippolytid shrimp, but amphipods and krill are particularly important for smaller fish [@love_certainly_2011]. Based on Ecopath foodweb modeling, the highest sources of predation mortality on the functional group Slope Rockfish from greatest to least are: Sablefish, skates, northern fur seals and California sea lions.

## Historical and Current Fishery Information
`r Spp_short` are not targeted by a specific fishery, but are desirable and marketable, thus are typically retained when captured.  They are often caught in bottom trawl, mid-water trawl, and longline fisheries.  Small numbers have been observed in pot, shrimp, and recreational fisheries.

Longline catches of `r Spp_short` are present from the turn of the century and continue in recent years, targeting Sablefish and halibut. 

After many attempts to start trawl fisheries off the west coast of the U.S. in the late 1800s, the availability of the otter trawl and the diesel engine in the mid-1920s helped the trawl fisheries expand [@douglas_species_1998]. The trawl fisheries became established during World War II when demand increased for bottomfish. A mink food fishery also developed during World War II [@jones_oregon_1961], and post-war catches for rockfishes, including `r Spp_short`, increased [@niska_species_1976]. Between the mid-1960s and mid-1970s, foreign trawl fleets from the former Soviet Union, Japan, Poland, Bulgaria, and East Germany targeted aggregations of Pacific Ocean Perch in the Northeast Pacific Ocean, in the waters off the U.S. West Coast [@love_rockfishes_2002] until the EEZ was implemented in 1977 [@rogers_species_2003]. 

Also, large-scale harvesting of Pacific Hake in the U.S. began in late-1960s, when factory trawlers from the Soviet Union and other countries began targeting this stock. `r Spp_short` was commonly caught in this fishery. After the 200 mile U.S. Exclusive Economic Zone was declared in 1977 and a joint-Venture fishery was initiated between U.S. trawlers and Soviet factory trawlers acting as mother-ships (larger, slower ships for fish processing and storage while at sea). By 1989, the U.S. fleet capacity had grown to a level sufficient to harvest the entire quota and no further foreign fishing was allowed. 

Since 1977, landings of rockfish were higher until management restrictions were implemented in 2000. `r Spp_short` inhabit deeper water as adults, which were fished less often historically. More detailed information about the fisheries by state is given in @sec-fishery_data, where the reconstructed catches are discussed. The catches fleet as well as for the Pacific whiting at-sea fleet are shown in @fig-landings.

## Summary of Management History and Management Performance
`r Spp_short` has been a small component of groundfish fisheries and catches of `r Spp_short` have been governed by restrictions on assemblages of species, of which these species are a member. However, the distribution of fishing effort in areas where `r Spp_short` might be encountered has also been affected by catch restrictions on co-occurring, rebuilding species, as well as associated area closures instituted to promote rebuilding. The first imposed landings limits on a coastwide Sebastes complex (`r Spp_short` being one of the 50 rockfishes in the complex) were instituted in 1983. 

This complex was divided in to two management areas north and south of $43^\circ 00'$ N in 1994. Ongoing concern that shelf and slope rockfishes may be undergoing overfishing led the attempt by @rogers_status_1996 to describe the status of most rockfishes in the Sebastes complex. `r Spp_short` information content was low. To  estimate exploitation rates of Rougheye Rockfish @rogers_status_1996 assumed fishing mortality was equal to natural mortality and used the AFSC/NWFSC Triennial Shelf Survey to calculate an average biomass. The analysis found that the stock was undergoing very high exploitation rates in both management areas. 

The dividing line between the northern and southern management areas was shifted to 40º10’ N latitude in 1999 and the Sebastes complex was subsequently divided into nearshore, shelf, and slope complexes in 2000. Rougheye Rockfish has been managed under trip limits for the minor slope rockfish complex in both north and south management areas since this time.

@tbl-management_summary summarizes major management changes since 2000. Some important changes include the implementation of Rockfish Conservation Areas (RCA’s) in 2002, the beginning of trawl rationalization in 2011, and the lifting of the RCAs beginning in 2020 with the removal of the trawl RCA in Oregon and California and loosening restrictions in the non-trawl RCAs in 2023 and 2024.

Though managed as part of a complex, OFL contributions for `r Spp_short` were calculated using DB-SRA in 2010 for the 2011-2012 management cycle. This lead to the observation that recent catches had frequently exceeded the OFL contribution estimated using data-poor, catch-only methods provided a strong indication that a more thorough evaluation of `r Spp_short` stock status and sustainable harvest levels be undertaken, using all available data. A full assessment of `r Spp_short` was undertaken in 2013 and indicated the stock complex was above management target levels [@hicks_status_2013]. Recent management performance for `r Spp_short` is provided in @tbl-management-performance for north and south of 40'10. `r Spp_short` is managed as a part of the minor slope rockfish complex. 

<!-- Management performance, including a table or tables comparing Overfishing Limit (OFL), Acceptable Biological Catch (ABC), Annual Catch Limit (ACL), landings, and catch (i.e., landings plus discard) for each area and year. Groundfish assessments that estimate dead discarded catch must include a disclaimer noting that total mortality estimates from the WCGOP and from the stock assessment may differ due to the use of different methods. Investigation into how these methods differ is beyond the scope of a benchmark assessment. The rationale for modeling discard mortality can also be provided. This should be included in all update assessments.  -->

## Fisheries off Canada and Alaska
`r Spp_short` are distributed throughout Canada and Alaska and are commonly caught in trawl and longline fisheries.  Alaska conducts assessments biennially for the Rougheye/Blackspotted complex, and two have been recently done: one for the Bering Sea and Aluetian Islands [@spencer_assessment_2023] and the other for the Gulf of Alaska [@sullivan_assessment_2023]. Canada completed an assessment in 2020 [@starr_rougheyeblackspotted_2020].  The fisheries and assessments for each country are described below.

Rougheye Rockfish have been managed as a bycatch-only species in Alaska since 1991 with catches ranging between 130 and 2,418 mt and peaking in the late 1980s and early 1990s [@sullivan_assessment_2023]. Generally, about 55-75% of the catch are trawl-caught and 30-45% from hook-and-line (mainly, longline) fisheries. Since 2017, the move to pot gear in the Sablefish fishery has decreased the longline catches. Discards since 2013 have ranged from 11.6% (in 2023) to 45% (in 2018). The Rougheye/Blackspotted complex catch levels generally are between 20% and 60% of the Total Allowable Catch since 2005 when the complex began to be managed separately. The most recent age-structured integrated stock assessments of this complex in the Bering Sea and Aluetian Islands [@spencer_assessment_2023] and for the Gulf of Alaska [@sullivan_assessment_2023] do not indicate either overfishing or the stocks being overfished.

Canada identified two species of Rougheye Rockfish (Type I and Type II) in 2007 and designated both species of special concern, which means that they may become threatened or endangered because of a combination of biological characteristics and identified threats [@cosewic_2007]. This designation was given because biomass estimates were uncertain and no strong trends were observed, there is evidence of truncation of the age distribution and overall mortality has doubled, it is a long-lived, low-fecundity *Sebastes* species, which is susceptible to population collapse and slow recovery, and because of the difficulty in separating the two species may result in potential impacts on one of the species going unnoticed. Subsequently, the species were identified as Rougheye Rockfish and Blackspotted Rockfish and a management plan was created in 2012 with a goal of sustaining the populations of Rougheye and Blackspotted Rockfishes [@fisheries_and_oceans_canada_management_2012]. Five high priority and seven low priority actions have been identified to address the threats to the populations and support the management goal. 

The first Canadian stock assessment for these species, using a integrated catch-at-age model, was conducted in 2022 to estimated stock status of two Rougheye/Blackspotted (REBS) Rockfishes management units (REBS north and REBS south) a the beginning of 2021. The REBS north stock was in the healthy zone in the reference model. The REBS south stock was likely in the healthy zone, but with an elevated possibility of being in the cautious zone. 
