## Model Diagnostics


### Model Convergence and Acceptability {#sec-model-convergence}

While there is no definitive measure of model convergence, several measures are routinely applied. These criteria include a low maximum gradient (`r model_output$maximum_gradient_component`), inversion of the Hessian (passed), acceptable fits to data (passed), and reasonable parameter values (passed). 

Model efficiency was explored by doing a short run Bayesian analysis using the Random Walk Metropolis with 2,000 draws, keeping all the draws and examining the fast mixing parameters. Those estimated parameters that do not move much from the initial values slow the model down and are recommended to be fixed at the starting value [@monnahan_overcoming_2019]. No additional parameters were fixed based on this analysis (@fig-pairs_plot_fast).

An extra effort was given to ensure the model did not rest on a local likelihood minimum. This was done by starting the minimization process from dispersed parameter values away from the maximum likelihood estimates to determine if the approach found a better model fit (i.e., minimum negative log-likelihood value). Starting parameters used a jitter shift value of 0.01 and 0.05. Both jitter scenarios were repeated 100 times with 78 out of 100 (jitter 0.01) and 49 out of 100 (jitter 0.05) runs returned to the reference model likelihood (@fig-jitter001 and @fig-jitter005). Out of the combined 200 jitter runs, a better fit, lower negative log-likelihood model was not found in any of the remaining runs. The reference model did not experience convergence issues when provided reasonable starting values. Through the jittering and likelihood profiles, the present reference model represents the best fit to the data given the assumptions. 

### Retrospective Analysis

A five-year retrospective analysis was conducted by running the model and sequentially removing one year of data up through minus 5 years. Retrospective spawning output (@fig-retro-so) and relatives stock status (@fig-retro-status) show a distinct sensitivity to the removal of the recent data. Both the scale and status drop when data from most recent year is removed.  Once two years are removed, the model returns to something more similar to the reference model. After several additional model runs to explore why this sensitivity is occurring, it was clear that removal of the most recent age data in all fleets causes this pattern. Looking at each of the fisheries mean age data time series, all 4 sources of age data, which have different selectivities, but all of which to some degree include bigger and older individuals, show the consistent pattern of decreasing mean age from 2022 to 2023, and an increase in 2024. These changes, except for the large increase in scale for the -4 and -5, are within the uncertainty of the reference model. The Mohn's rho evaluation of the degree of retrospective pattern show the data peels are below significant levels for stock status, and above only for the -4 and -5 year peels that show extremely high spawning output values. 



### Fits to the Data

#### Indices of Abundance

The fits to the 4 available indices of abundance demonstrate little information content in the survey indices (@fig-index-tri to @fig-index-wcgbts). The are all mostly flat with large uncertainty. Such lack of contrast and high uncertainty in the abundance measure indicate the indices contribute little influence to the model (see data sensitvities section below for more details).

#### Lengths

Fits to the length data are examined based on the Pearson residuals-at-length, the annual mean lengths, and aggregated length composition data for the commercial and recreational fleets. The aggregate fit to each length composition demonstrates acceptable fits to each fleet and survey source (@fig-agg-len-fit). One noticeable behavior is the trade-off in fit between the fit in the bottom trawl fishery versus the fit in the at-sea hake fishery. This current model specification was the best trade off of fits between the two. 

Fits to the annual length composition are provided for the following fisheries and surveys:

<u>Fishery</u>

* Bottom trawl (@fig-len-fit-bt-1 and @fig-len-fit-bt-2)
* Bottom trawl discard (@fig-len-fit-btdis)
* Non-trawl (@fig-len-fit-nt-1 and @fig-len-fit-nt-2)
* Non-trawl discard (@fig-len-fit-ntdis)
* Midwater trawl (@fig-len-fit-midt)
* At-sea hake (@fig-len-fit-ashop)

<u>Surveys</u>

* Triennial (@fig-len-fit-tri)
* Alaska slope (@fig-len-fit-akslope)
* West Coast Groundfish Bottom Trawl (@fig-len-fit-wcgbts)


Pearson residuals of fits to the fishery (@fig-peasrson-resids-fishery) and survey (@fig-peasrson-resids-survey) length data are reasonably small with no distinct patterns. 

Model fits to the mean lengths, assuming Francis data-weighting of 1 and blocking patterns, demonstrate fits within the error bars of most years and no strong residual patterns (@fig-meanlt-bt to @fig-meanlt-wcgbts). A notable observation in the means lengths within blocks generally show a lack of trend, not surprising given how many years an individual may be at its maximum size. This is in contrast with the age data that do show more nuances in age structure trend (see next section on age fits for more detail). This demonstrates the general lack of contrast in the length data.


#### Ages

##### Conditional Age at Length

Fits to the sex-specific conditional age at length data are examined based on the age-at-length Pearson residuals, the annual mean ages, and mean age at length by year for the four fishery and one survey source. Pearson residuals were of reasonable size with no distinct patterns (@fig-peasrson-resids-age-bt1 to @fig-peasrson-resids-age-wcgbts3), as most of the residuals were small and not noteworthy and demonstrate the expected shape of the growth curve. There is more contrast in the age data compared to the length data (@fig-trawl-mean-caal to @fig-wcgbts-mean-caal). While the mean age for fisheries varied by gear selectivity (25-35 years for bottom trawl; 30-40 years for non-trawl; ~40 for midwater trawl; 40-50 years for the at-sea hake fishery), one commonality was the increase in mean age in the last year of the model. This consistent increase in mean age across fisheries with different selectivities is important to remember when interpreting the retrospective pattern of the model. Mean age for the West Coast Groundfish Bottom Trawl survey, which catch much smaller and less larger individuals, fluctuated around 20 and did not show an mean age increase in the final year. Fits to the mean ages by length bins show acceptable fits consistent with model expectations (@fig-call-plot-bt1 to @fig-call-plot-wcgbts6).

##### Marginal Age

Marginal age compositions are not fit in the model, but they are included in order to see how well they fit the reference model without influencing the likelihood (@fig-marage_bt to @fig-marage_wcgbts). Marginal length and age composition cannot be used in the same model because of the overlap of fish in both samples. This is why ages conditioned on lengths are often used with the length compositions. But it still stands that age compositions, instead of lengths, could be used. So adding the marginal age compositions passively (i.e., not contributing to the overall likelihood of the model) can offer insight into how consistent they are with the current model fit. Overall the realized fits are good.  

## Model Results 
As a supplement to the model results figures included in this report and described below, a full set of diagnostic plots created by the {r4ss} package is available at https://github.com/shcaba/REBS-2025 along with the Stock Synthesis input files.

### Parameter Estimates

Estimated parameters by category are given in @tbl-n-param. The reference model parameter estimates along with asymptotic standard errors are shown in @tbl-param and the likelihood components are shown in @tbl-likes. Estimates of derived outputs and reference points and approximate 95 percent asymptotic confidence intervals are provided in @tbl-ref-points. 

The estimate of female natural mortality is higher than the assumed value for males, which fits the expectation given the oldest individuals in the population are all males, and within reason (`r round(model_output$parameters[model_output$parameters$Label == "NatM_uniform_Fem_GP_1", 3],3)`) given the oldest individual aged female sampled. 

Estimated growth curves in this assessment is similar to the growth curve estimated in 2013 assessment (@fig-vbgf), though with some important difference. The estimated $L_{\infty}$ and $k$ for both sexes were slightly greater and lower than the values estimated externally, respectively. This is not surprising, given external fits assume all variability is in the length at age, while the model incorporates ageing error and selectivity effects. Both females and males reach their maximum size at relatively young ages (< half their presumed longevity), thus possibly limiting the information content of lengths on the underlying age structure.

Estimated ending selectivity curves for each fleet and survey (@fig-sel-all) are a mix of dome-shaped (for bottom trawl gears) and logistic (for mid-water gears) and look plausible given the biology (i.e., as a model convergence check for realism, the selectivity curves must look plausible). The surveys show the greatest degree of dome-shapeness, while the fisheries selectivities included sampling of at least some of the larger individuals. Time-varying selectivity showed mostly the same functional form for each fleet, despite changes in the selectivity, except for the non-trawl fishery, which changed from dome-shaped in the earlier blocks to logistic in the most recent time period (@fig-sel-tv-fisheries and @fig-sel-tv-surveys). The realized age selectivity based on the length-based selectivity show even more truncated sampling of older individuals in some of the dome-shaped fleets (@fig-sel-all-age). Values for the estimated selectivity parameters are in @tbl-param.

The estimate of initial recruitment ($lnR_0$) is much higher than the previous assessment (`r round(model_output$parameters[model_output$parameters$Label == "SR_LN(R0)", 3],2)` vs. 6.20). While this is a large increase in the scale of the stock, a value of `r round(model_output$parameters[model_output$parameters$Label == "SR_LN(R0)", 3],2)` is not unusual for shelf and/or slope rockfish species. The estimate of ($lnR_0$) for `r Spp_short` is well within the range of other groundfishes in similar habitat (@fig-lnR0). And given this assessment is for two species, the estimate for ($lnR_0$) is reasonable. There is also a very large variability estimated for this parameter (coefficient of variation = `r round(model_output$parameters[model_output$parameters$Label == "SR_LN(R0)", 11],2)`), thus scale is generally very poorly informed in this model. 

### Population Trajectory

The predicted spawning output (in trillions of eggs) is provided in @tbl-ts and plotted in @fig-spawnout. Estimated spawning output shows a decline in the early part of the time series due to poor recruitment, but rise before 1980 from offsetting recruitments (all not well informed), followed by a slight decline during the heaviest period of fishing, though moderated by recruitments in several years over the past 4 decades. The uncertainty around the estimate of spawning output is enormous, highlighting a major feature of the model output.

Relative spawning output never declined below the management target ($SO_{40\%}$) and currently is estimated well above the target (@fig-depl; `r round(model_output$derived_quants[model_output$derived_quants$Label == 'Bratio_2025','Value'], 2)` in `r model_output$endyr + 1`). The uncertainty in stocks status also does not support the stock being below the management target of $SO_{40\%}$. This uncertainty is based only on the asymptotic estimation of variance from one risk neutral model. Further uncertainty exploration is needed to capture a fuller range of uncertainty (see Sensitivity section).

The time series of estimated annual recruitment deviations are shown in @fig-recdevs. The bias adjustment plot (@fig-biasramp) indicates that the most informed recruitment deviations occur after 1980. While post-1980 is the most informed, the recruitment deviations before that time period, while less assure, are important for the model to prepare the population structure for the upcoming increase in fishing while reconciling weak, but still present, signals in recruitment from the biological compositions that can contain information on recruitment for decades given the long-liveness of these species. Sensitvities to when recruitment estimation begins in the model is shown in the Sensitivity section. Numbers of age-0 individuals indicate those years of particularly strong recruitment (@fig-recruits). Noticeable recruitment years are seen in 1988, 1993, 1999, 2008, 2010, 2012, and 2017 (@fig-SR). This amounts to roughly two notable recruitments per decade. Given this assessment is tracking two species, it is hard to tell whether the species are synchronized or showing their own recruiment pulse in this signal.

