## Characterizing uncertainty

### Sensitivity Analyses {#sec-assmt-sens}

Sensitivity analyses were conducted to evaluate model sensitivity to alternative data treatment and model specifications.

#### Data treatment sensitivities

Data treatments explored the removal of data types (indices and biological compositions), data weighting options and ageing error treatment. 

##### Removal of data sources 

The following data source sensitivities were explored:

* Remove a single index of abundance (Triennial, Alaska slope, NW slope, WCGBTS, all indices)
* For each fleet and index, including discard fleets, removal of length composition data
* For each fleet and the WCGBTS, removal of age composition data

Likelihood values and estimates of key parameters and derived quantities from each data source removal sensitivity are available in @tbl-sensitivities-like-indices to @tbl-sensitivities-like-age. Additionally, time series of spawning output and relative spawning output are shown in @fig-sens_indices_spout to @fig-sens_age_relsp. Derived quantities relative of all data removal sensitivities to the reference model are summarized in @fig-sens_sum_data. Generally, the removal of indices of abundance decreased both the spawning output and the relative spawning output as compared to the base model (@fig-sens_indices_spout and @fig-sens_indices_relsp). Of these, the WCGBTS appears to have the most significant impact. Removal of the bottom trawl (bottom trawl + discards) and non-trawl (non-trawl + discards) fishery length compositions decreased the spawning output and the relative spawning output, whereas removal of the mid-water trawl and the at-sea hake length compositions increased the spawning output and relative spawning output (@fig-sens_lens1_spout and @fig-sens_lens1_relsp). Of the length composition removals, the most influential data sources appear to be the fishery fleets and removal of the survey length compositions had a limited impact on both spawning output and relative spawning output compared to the base model (@fig-sens_lens2_spout and @fig-sens_lens2_relsp). Finally, the removal of any age composition data source decreased the spawning output, with the exception of the mid-water trawl ages, and decreased the relative spawning output (@fig-sens_age_spout and @fig-sens_age_relsp). Again, the WCGBTS appears to be the most influential of the data sources with age composition information.

  	
##### Data weighting

The following data weighting sensitivities were explored:

* No data-weighting
* Dirichlet data-weighting
* McAllister-Ianelli data weighting

Likelihood values and estimates of key parameters and derived quantities from each data weighting sensitivity are available in @tbl-sensitivities-data-weighting. Comparison plots for the results relative to the reference model are in @fig-sensi-data-wt and @fig-sensi-RE-data-wt. Each data weighting scenario up-weighted the influence of the length data relative to the age data. This resulted in a large drop in the stock scale, but little change in the high stock status. These changes were within the uncertainty of the base model, though at the low end for the stock scale.


##### Ageing error

The following ageing error sensitivities were explored:

  * No Ageing error for all sources (unbiased and precise ages)
  * No ageing error for each source at a time

Likelihood values and estimates of key parameters and derived quantities from each ageing error sensitivity are available in @tbl-sensitivities-age-error. Comparison plots for the results relative to the reference model are in @fig-sensi-ageing-error and @fig-sensi-RE-ageing-error. A drop in both stock scale and stock status is generally observed when the ageing error is removed. One notable observation is that the recruitment events become less resolved and variance increases in lengths at age when ages are assumed biased and precise. When the ages are taken as true, all variation between lengths and ages are interpreted in the lengths, while the recruitment must interpret the age composition precisely, thus assigning positive recruitment deviations to years adjacent to strong recruitment years seen in the reference model. Having more positive recruitment can compensate for a lower initial stock size, causing the initial stock size to decrease. All in stock scale and status changes were within the uncertainty of the base model.


#### Sensitivities to Model Specification  {#sec-senstivities}

Model specifications looked at the treatment of life history parameters selectivity and the estimation of recruitment. All scenarios match the reference model specifications in all other aspects unless otherwise stated.

* Life history parameters

	* Natural mortality ($M$)

		1. Estimate male $M$
		2. Fix $M$ to 2013 value
		3. Lorenzen age varying $M$
	
	* Growth parameters

	 	4. Fix all growth parameters to external values

	* Reproductive Biology

		5. Proportional fecundity to weight
		6. Functional maturity at age
		7. Functional maturity at length for Blackspotted Rockfish
		8. Functional maturity at length for Rougheye Rockfish
		9. Biological maturity at length

	
Summaries of the model results for these sensitivities are presented in @tbl-sensitivities-life-history_1 and @tbl-sensitivities-life-history_2, @fig-sensi-LH and @fig-sensi-RE-LH. Additionally, the scale comparisons minus the estimation of $M$ scenario is provided in @fig-sensi-LH-so as that model scenario showed such higher estimates of scale to obscure all other models. Note also that the proportional fecundity scale measure is in metric tons, not trillions of eggs, and thus are not comparable in scale to the other models.

None of the sensitivities were found to be outside of the reference model uncertainty for scale or stock status (@fig-sensi-RE-LH). In particular, the stock status was highly conserved over these sensitivities, while both the initial and final stock scales were more sensitive (but still within the uncertainty of the reference model). In general, higher natural mortality assumptions reduced the stock scale when the bottom trawl and non-trawl fisheries were dome-shaped, as did the fixing of growth to the external model estimates. For reproductive biology, scale decreased if either age at maturity of functional length at maturity for Blackspotted Rockfish only was used. But scale increased if either functional maturity for Rougheye Rockfish only or biological maturity was used. The reference model, a mix of both species maturity at length, settled the scale inbetween each individual species-specific functional maturity model. For this long-lived species and future consideration, age may be a more precise determination of maturity (because there is a wide range of lengths per age) than length; however, age data is more limited and further information is encouraged to build this relationship. 


* Recruitment estimation

 	13. No recruitment estimation
 	14. Estimate from 1940 onward
	15. Estimate from 1980 onward

Likelihood values and estimates of key parameters and derived quantities from each sensitivity are available in @tbl-sensitivities-sel-rec. Comparison plots for the results relative to the reference model are in @fig-sensi-SelRec and @fig-sensi-RE-SelRec. Few (starting in 1980) or no recruitment deviation estimation leads to larger stock scale required to make up for the catch history and lack of recruitment compensation. There is a drop in stocks status when starting recruitment deviations in 1940, but more similar to the reference model. Stock status is steady in these scenarios and all uncertainty is included in the reference model uncertainty (@fig-sensi-RE-SelRec).

* Selectivity

	16. Logistic selectivity for all fisheries and time blocks
	17. Logistic selectivity for bottom trawl fishery
	18. Logistic selectivity for non-trawl fishery
 


The model is much more sensitive to the assumption that fishery selectivity for the bottom trawl and/or non-trawl are logistic. These produce the most sensitive of all the explored alternative models scenarios in both scale (lower) and stock status. In all of these instances, the uncertainty is outside that of the reference model @fig-sensi-RE-SelRec. The reason these are less likely scenarios can be seen in the notably degraded fits to the bottom trawl and/or non-trawl length compositions (@fig-sensi-logsel_fits). This supports the choice for the change in the reference model from the previous stock assessment to consider dome-shaped selectivity for those two fisheries. Given the only scenarios to fall below the low uncertainty treat the bottom trawl as logistic selectivity, it is a good candidate for a lower state of nature (and not a risk neutral model).


### Likelihood profiles {#sec-profiles}

Likelihood profiles were conducted for the the log of initial recruitment (ln($R_0$)), steepness ($h$), and female male natural mortality ($M$) with female natural mortality estimated. Likelihood profiles were conducted by fixing the featured parameter(s) at specific values across a range of values and estimating all remaining parameters. A likelihood profile offers insight into model sensitivity to changing model parameter values, while providing an additional way to describe uncertainty in the parameter by identifying the range of parameters within 1.96 likelihood units of the reference model.

#### Initial unfished recruitment ($lnR_0$)

The profile on the assumption of $lnR_0$ (that sets the initial scale of the population) demonstrates the data and current model specification support value of $lnR_0$ greater than 6.25, with a steep increase in likelihood difference as $lnR_0$ goes lower (@fig-likeprof-lnR0-parm). The is the expectant increase in scale across increasing $lnR_0$ values for both initial and ending spawning output. The final spawning output goes down quicker than the initial spawning output, leading to a lower stock status. Even at very low $lnR_0$ values, the stock does not drop below the target reference stock status.

The component likelihoods show a clear conflict in the length and age data, with lengths pulling for lower $lnR_0$ values and ages for higher $lnR_0$ values (@fig-likeprof-lnR0-components). While this is a consistent signal in the ages, the individual length sources also show conflict, with the bottom trawl length data pulling for higher $lnR_0$ values. 

#### Steepness ($h$)

The profile on the assumption of $h$ (defining productivity of the stock) demonstrates the data and current model specification do not demonstrate support for a particular steepness value (@fig-likeprof-h-parm). The change in scale and stock status is small and mostly flat through a large range of $h$ values. The lack of information on $h$ is seen across the data likelihood components  (@fig-likeprof-h-components). Given the strong signal of a health stock with little contrast in historical population trajectory, these are expected results. This strongly supports the pre-specifying of this value, but also demonstrates the low sensitivity to pre-specifying this value.

#### Male Natural Mortality ($M$)

The profile on the assumption of male $M$ (while still estimating female $M$) demonstrates the data and current model specification support a higher value of male $M$ than what is being used in the reference model (@fig-likeprof-M-parm). This uncertainty has a much larger expression in the scale than in the stock status, and one major reason the model estimated uncertainty in scale is so large. It is also a reason why only female $M$ was estimated. Comparing the sex-specific values of $M$, females are always higher than males (@fig-likeprof-M-sex). Regarding stock status, there were no explored $M$ values that caused the stock to go below the target reference point.

The component likelihoods show a some conflict in the length and age data, with lengths (mostly the non-trawl lengths; most of the other length contain no information) pulling for higher $M$ values and ages for lower $M$ values (@fig-likeprof-M-components). As noted when building the reference model, ages are believed to contain more information on natural mortality than lengths. Consider that component likelihood profile, the reference model value for male $M$ is the lowest support by the age data, and was chosen to avoid the fast increasing scale estimates. The integrated assessment approach does not allow for ages only to define the estimation of $M$, and thus the choice to pre-specify one $M$ value and estimate the other in order to anchor to compensate for the incursion of the length data signal in the estimation of $M$.

### Summary of Sources of Uncertainty and States of Nature

Over the many different sources of potential uncertainty, patterns in how these sources affect scale and status emerge (@tbl-uncertainty_summary). These sources highlight conflicts in data and selectivity assumptions, while also emphasizing key uncertainty in natural mortality. Specifically, there are many ways to make the reference model at a higher or lower scale and/or stock status (@tbl-uncertainty_summary). In building states of nature and around this risk neutral reference model, the two key axes of uncertainty are based around the treatment of natural mortality and selectivity. The high state takes the estimation of selectivity (allowing dome-shaped if chosen) and adding the estimation of $M$ for both sexes (Model specification sensitivity scenario #1). The low state of nature assume the reference value of male $M$ with an estimated female $M$ and constraining the selectivity of bottom trawl and non-trawl fisheries to logistic (Model specification sensitivity scenario #16). These produce a very wide set of uncertainties around both scale and stock status (@fig-states-of-nature). If these are treated as an ensemble, with high and low states of nature assuming a weight of 12.5% and the reference model the remaining 75%, the uncertainty range can be expressed as one model output (@fig-ensemble). 


### Unresolved Problems and Major Uncertainties
The absolute size of `r Spp_short` populations are highly uncertain. `r Spp_short`  is relatively lightly exploited stock, most likely because `r Spp_short` is associated with steep slopes and boulder habitats, difficult to access with bottom trawl gears. Plus, it occurs in the northern part of the assessed area (off Oregon and Washington), and is only rarely taken by fisheries in California. Given this relatively light exploitation, we did not observe large contrasts in the stock dynamics. Such contrasts between periods of depletion, followed by recovery (a.k.a. “two-way trips”) provide more about carrying capacity, the intrinsic growth rate as well as scale of the population.

Through extensive explorations, we found that stock scale is sensitive to assumptions about shape of the selectivity curves, especially for the bottom trawl. In the previous assessment all fleets (except for Triennial Survey) were assumed asymptotic. In this assessment, we provide flexibility for the bottom trawl and non-trawl fleets and bottom trawl surveys to estimate dome-shaped selectivity curves. Changes in selectivity assumptions enabled substantially improved fits to length and age composition data in fisheries and surveys, but also resulted in a substantial increase of stock scale.

Stock scale is also sensitive to assumptions about natural mortality. `r Spp_short` is one of the longest lived species of rockfish on the West Coast, with maximum ages of 169 years in this assessment. Individuals as old as 205 years are reported in literature. It is therefore likely that natural mortality for `r Spp_short` is lower than for other rockfish species. With length and age data available only for years after 1994, there is limited ability to monitor the long-term changes of aging cohorts.  Therefore, estimates of natural mortality are uncertain.  This assessment attempts to capture uncertainty in this parameter and integrate it into the derived biomass estimates by estimating natural mortality for females, while fixing the male natural mortality at the value from meta-analytical study. 
