# Management 

## Reference Points

Reference points were calculated using the estimated fishery selectivity and removals in the most recent year of the model (2024, @tbl-ref-points). Reference points were based on the rockfish $\text{F}_{MSY\%}$ proxy ($\text{SPR}_{50\%}$), target relative biomass (40%), and estimated selectivity and catch for each fleet (@tbl-ref-points). The proxy MSY values of management quantities are by definition more conservative compared to the estimated MSY and MSY relative to 40% of unfished spawning output because of the assumed steepness value. Sustainable total yield, removals, using the proxy $\text{SPR}_{50\%}$ is `r round(model_output$derived_quants[model_output$derived_quants$Label == 'Dead_Catch_SPR', 'Value'], 2)` mt. The spawning output equivalent to 40% of the unfished spawning output ($\text{SO}_{40\%}$) calculated using the SPR target ($\text{SPR}_{50\%}$) was `r format(model_output$derived_quants[model_output$derived_quants$Label == 'SSB_SPR', 'Value'],scientific = F)` trillions of eggs. 

The 2025 spawning output relative to unfished equilibrium spawning output, based on the 2024 fishing year, is `r 100*(round(model_output$derived_quants[model_output$derived_quants$Label == 'Bratio_2025', 'Value'], 2))`%, above the management target of 40% of unfished spawning output (@fig-depl). The fishing intensity, $1-SPR$, was below or just slightly above harvest rate limit ($SPR_{50\%}$) from the mid-1980s through the 1990s. Removals since 2000 have been below the point estimate of potential long-term yields calculated using an $\text{SPR}_{50\%}$ reference point (@tbl-ts and @fig-one-minus-spr). The equilibrium estimates of yield relative to biomass based on a steepness value fixed at `r round(model_output$parameters[model_output$parameters$Label == "SR_BH_steep","Value"], 2)` are provided in @fig-management-yield, where vertical dashed lines indicate the estimate of fraction unfished at the start of 2025 (current) and the estimated management targets calculated based on the relative target biomass (B target), the SPR target, and the maximum sustainable yield (MSY).

The relative biomass and the ratio of the estimated SPR to the management target ($\text{SPR}_{50\%}$) across all model years are shown in @fig-management-phase where cooler colors (purple) represent early years and warmer colors (yellow) represent recent years. The stock staus has not decreased below the target relative biomass, and fishing intensity (except for in 1995) has been below the target fishing intensity based on $\text{SPR}_{50\%}$.

## Management performance

In the last ten years total dead catches of `r Spp_short` have been below the annual catch limit. The last ten years total dead catches for `r Spp_short` against he overfishing limits (OFLs), the acceptable biological catches (ABCs), the annual catch limits (ACLs) are shown in @tbl-man-management. 

## Harvest Projections and Decision Table

The `r Spp_short` assessment is being considered as a Category 1 assessment with a $P^*$ = 0.45, $\sigma$ = `r round(model_output$OFL_sigma,2)` (estimated within the model, see @sec-uncertainty) and a time-varying buffer applied to set the ABC below the OFL. These multipliers are also combined with the rockfish MSY proxy of SPR\textsubscript{50} and the 40-10 harvest control rule to calculate OFLs and ACLs. Projections of the overfishing limit, acceptable biological catch, and annual catch limit, all based on a $P^*$ of 0.45 and a log-space standard deviation of the overfishing limit ($\sigma$) of `r round(model_output$OFL_sigma,2)` are included in @tbl-man-projections. Assumed catches for 2025 and 2026 for this projection were provided by the PFMC Groundfish Management Team, and catches from 2027 onward assume full attainment of the acceptable biological catch.

No decision table needed in draft assessments undergoing review.

## Evaluation of Scientific Uncertainty {#sec-uncertainty}

The model estimated uncertainty ($\sigma$) around the 2025 spawning output for is `r round(model_output$Pstar_sigma,2)`. These values underestimate the overall uncertainty as they do not incorporate the model structural uncertainty and do not account for any time-varying dynamics other than recruitment. The estimated uncertainty values are higher than the Category 1 default of 0.5, so all projections will use the estimated $\sigma$. The alternative states of nature used to bracket uncertainty in the decision table assist with encapsulating model structure uncertainty.

{{< pagebreak >}}

## Risk Table

Below is a risk table for `r Spp_short` to document 1) ecosystem and environmental factors, 2) stock assessment data inputs, and 3) assessment model fits and structural factors that could potentially affect stock productivity and/or uncertainty arising from the stock assessment (see text). Level 1 is favorable/less uncertain, Level 2 neutral, and Level 3 unfavorable/more uncertain

```{r, results = "asis"}
#| label: 
#| echo: false
#| warning: false

risk <-read.csv(here::here("Document","report", "tables_4_doc", "RiskTable_20250618.csv"))
risk|>
  gt::gt() |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  gt::cols_label(
    Ecosystem.and.environmental.conditions = "Ecosystem and environmental conditions",
    Assessment.data.inputs = "Assessment data inputs",
    Assessment.model.fits.and.structural.uncertainty = "Assessment model fits and structural uncertainty"
  ) |>
  gt::cols_width(
    everything() ~ px(200)
  ) |>
  gt::as_latex()

```

### Rating the Ecosystem and Environmental Conditions

To understand the impact of ecosystem and environmental conditions on `r Spp_short`, we evaluated recent trends in drivers of recruitment, predators, and prey, along with context from the climate vulnerability assessment (CVA) of @mcclure2023. We did not consider non-fisheries human activities during this evaluation.  In considering ecosystem and environmental conditions (column 1), we focus on recent trends over the last 5 years; we assume that long term trends are implicitly represented in the stock assessment and do not represent notable changes that warrant inclusion in the risk table. 

Overall we consider ecosystem and environmental conditions to be neutral (Level 2) with medium confidence based on high agreement among indicators and medium evidence, and no apparent concerns. We use this, plus information related to the stock assessment, to fill out the ‘risk table’ above, based on the framework outlined by the California Current Integrated Ecosystem Assessment (CCIEA) team [@Golden2024].

### Environmental Influences on Demographic Rates
#### Recruitment

Recruitment drivers of Rougheye and Blackspotted rockfishes are not well understood. Direct links between oceanographic conditions and `r Spp_short` young-of-the-year (YOY) have not been made, but a few conditions have been linked to YOY abundance across rockfish species in the California Current. Specifically, winter source water variability was linked to observed spring pelagic YOY abundance for ten species of winter spawning rockfish in the CCE. Cool/fresh conditions (minty) are indicative of subarctic conditions and are consistent with greater pelagic juvenile abundance of some rockfish species [@schroeder2019source;  @Santora_etal_2021]. Further work focused on conditions north of Cape Mendocino would be required to assess the relevance of these studies for `r Spp_short`. In general, there may also be value in considering other more common rockfishes as ‘proxies’ that signal good recruitment for rarer `r Spp_short`. @gasbarro_2025 found common trends in young-of-the-year rockfish within assemblages of similar species. However, it is unclear what other species might be used as proxies for Rougheye Rockfish, or might exhibit similar  recruitment patterns. 
 
Annual variation in the abundance and distribution of `r Spp_short` north of 42 °N was estimated from species distribution models fit to the WCGBTS. Fish ≤∙26 cm TL and approximately 6.5 years old were included as juveniles. Juvenile abundance appears to have declined slightly over time from higher levels in the 2003-2008 period, although the uncertainty around the estimates for each year are fairly large. Abundance has increased compared to a low-mark in 2011, but again there is a lot of uncertainty around the estimates. At present, juvenile abundance is moderate and slightly higher than the 2009-2014 period.  

### Distribution and Habitat Considerations
#### Stock Distribution

The distribution of `r Spp_short` biomass was examined using data from the WCGBTS and species distribution modeling (sdm) using sdmTMB. The sdmTMB model included spatial autocorrelation and a spatiotemporal field modeled as a random walk. The model did not include depth, and was fit as a delta-lognormal model and fit to data north of 42 °N. We did not see obvious changes in spatial distribution in `r Spp_short` biomass. Consistent with this lack of variability in the spatial distribution of Rougheye Rockfish, the center of gravity of `r Spp_short` biomass north of 42 °N showed little variation, increasing by less than 0.5 °N from 2003 to 2024. Juvenile `r Spp_short` distributions (<26 cm and 6.5 years old)  have been fairly stable through time but with interannual fluctuations. 

#### Predators and Prey

Given the diet importance of euphausiids (krill) and pandalid shrimp (including pink shrimp) for `r Spp_short`, recent trends in abundance of these invertebrate prey groups are relevant. The RREAS survey suggests average to above-average abundance of most forage groups, including krill, for Central California, and typical conditions for krill at the northern sites. Krill abundance at the Newport hydrographic line  (J. Fisher and K. Jacobson, pers.comm. 4/25/2025) suggest that krill was at typical levels over the last five years, but with high abundance of juvenile *E. pacifica* in October 2023  and of juvenile *T. spinifera* in July 2023. Additionally, krill length and biomass indices from the Trinidad Head survey line were near average for most of 2024. The coastwide krill abundance index, derived from acoustic data, was not available in 2024, but the 2023 values for this index in the relevant INPFC Vancouver and Columbia areas was moderate, and for example not as low as 2015. Though shrimp are important prey of `r Spp_short`, survey time series of shrimp abundance in US waters are lacking. However, commercial pink shrimp landings increased by 17% in 2024, though with no clear trend over the last 5 years. Overall, there is evidence for stable or slightly increasing forage (euphausiid and pink shrimp) in the last year.  

Predators that impose the largest amounts of predation mortality on `r Spp_short` can be identified from Ecopath food web modeling. The Ecopath models of Field (2006) and Koehn et al. (2016) were recently revised (C. Best-Otubu, P.Y. Hernvann, N. Lezama Ochoa, I. Kaplan, pers. comm.). The Ecopath model includes the functional group Slope Rockfish, which includes `r Spp_short`. The highest sources of predation mortality on Slope Rockfish, from greatest to least, derive from Sablefish, skates, northern fur seals, and California sea lions. Recent population increases (in the last 5 years) of Sablefish may impose some increased predation pressure on `r Spp_short`, but the linkage to `r Spp_short` is uncertain and can can only be inferred from ‘unidentified rockfish’ found in Sablefish stomachs. Predation by the other three predators (skates, fur seals, and California sea lions) is unlikely to have changed much in recent years, based on stable recent population dynamics (at least through recent assessments in 2019, 2013, and 2014 for these species, respectively). 

#### Trophic Overlap with Competitors

Major predators on krill (euphausiids) and pandalid shrimp can be identified via Ecopath modeling, to point to potential competitors for  Rougheye and Blackspotted rockfishes.  The recently revised Ecopath  model suggests that the highest sources of predation mortality (from greatest to less) on euphausiids are  Carnivorous zooplankton, Pacific Hake,  Large jellyfish, and Mesopelagic fish. Similarly, the highest sources of predation on pandalid shrimp are juvenile rockfish, Pacific Hake,  Other cephalopods, Greenstriped Rockish, and Benthic fish. Though we cannot quantitatively determine that forage abundance is limiting for Rougheye and Blackspotted rockfishes, there is some potential for competition by Pacific Hake and `r Spp_short`  for prey (euphausiids and pandalid shrimp). Based on the 2025 Pacific Hake stock assessment, Pacific Hake total biomass in 2025 is 72% higher in 2025 than in 2006, which was the base year for the Ecopath calculations. Further research could identify if such trophic overlap with Pacific Hake limits Rougheye and Blackspotted rockfishes and other species. 

### Climate Vulnerability Assessment Rank

The Rougheye Rockfish climate vulnerability assessment (CVA) of @mcclure2023 can provide context for this Risk Table.  @mcclure2023 found that Rougheye had a climate vulnerability of moderate, based on consideration of both exposure and sensitivity. Climate exposure was high, due largely to potential impacts on these species (and many others) from  ocean acidification, mean sea surface temperature, and declines in subsurface oxygen.  Biological sensitivity was ranked moderate, due to slow population growth rate and complicated reproductive physiology (live young).  We consider effects of climate exposure to be included in other sections of this risk table regarding distribution and prey abundance, and as a result the CVA ranking was not included in our final scoring of the ecosystem and environmental considerations.

## Research and Data Needs

There are many areas of research that could be improved to benefit the understanding and assessment of `r Spp_short`.  Below, we identify several of them that we consider particularly important.

*  Understanding the stock structure and biology of Rougheye and Blackspotted Rockfishes:  This assessment reports the status of `r Spp_short` as a pooled complex because it is extremely difficult to separate the catches of each species even in recent data, and attempting to do so would greatly increase the uncertainty in the predictions.  Because little is known about the respective biology and catch histories of the two species, it is unclear whether managing them as a complex may place one species at disproportionate risk of overfishing relative to the other.  Additional research that will provide insight into the distribution, life history, biological characteristics, and catch and discard profiles of the two species is recommended.  Such an endeavor would likely require the efforts of at-sea observers in all fleets, biologists aboard fishery-independent surveys, and port samplers along the entire West Coast requiring broad, inter-agency collaboration.

*  Understanding of coastwide stock structure, connectivity, and distribution:  This is a stock assessment for `r Spp_short` off of the west coast of the U.S. and does not consider data from British Columbia or Alaska.  Further investigating and comparing the data and predictions from British Columbia and Alaska to determine if there are similarities with the U.S. West Coast observations would help to define the connectivity between Rougheye Rockfish north of the U.S.-Canada border.

*	Natural mortality: Uncertainty in natural mortality translates into uncertain estimates of status and sustainable fishing levels for `r Spp_short`. `r Spp_short` are one of the longest lived species of rockfish, with maximum age as old as 205 years reported in @munkMaximumAgesGroundfishes2001. Assessment model was able to estimate female natural mortality, consistent with maximum age based meta-analytical prior, but with male natural mortality fixed at the median of the prior. The collection of additional age data and further research of the life-history of `r Spp_short` may improve our understanding of `r Spp_short` natural mortality.

* Developing and applying new age determination techniques, such as Fourier Transform Near-Infrared spectroscopy (FT-NIR): In recent years, progress has been made in using FT-NIR approach for fish age determination. At present, FT-NIR ages for `r Spp_short` have low agreement with traditional age estimates, and further research is needed before they are incorporated into stock assessment. 

* Historical landings and discards, including investigation of fisheries selectivity:  Substantial progress has been made in reconstructing historical landings of rockfishes on the U.S. West Coast, including those for `r Spp_short`. This assessment highlighted the importance of understanding fishery selectivity assumptions associated with removals and how fishery selectivity changes throughout the years. Further understanding in this area would help reduce uncertainty in the estimated scale of the stock.
